---
- hosts: all
  become: True
  tasks:
    - name: add docker repo 
      yum_repository: 
        name: docker
        description: docker repo
        gpgcheck: 0
        gpgkey: https://download.docker.com/linux/centos/gpg
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
        #baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
        state: present
      tags: docker_repo

    - name: add kubernetes repo 
      yum_repository: 
        name: kubernetes
        description: kubernetes repo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgcheck: 0
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg 
        state: present
      tags: kube


    - name: install docker pre-req
      yum: 
        name: "{{packages}}"
        #name: yum-utils,device-mapper-persistent-data,lvm2, kubelet, kubeadm, kubectl, epel-release, docker-ce, git, pyOpenSSL
        state: present 
      vars:
        packages:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - kubelet
          - kubeadm
          - kubectl
          - epel-release
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - git
          - pyOpenSSL
        notify:
          - docker status
      tags: packages 

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        group: docker
      tags: add_vag

    - name: create directory 
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /etc/systemd/system/docker.service.d
        - /etc/docker
      tags: create_dir 

    - name: install docker pre-req
      copy: 
        src: daemon.json 
        dest: /etc/docker/daemon.json 
      tags: docker_conf


    - name: start and auto-start docker
      service: 
        name: docker
        state: started
        enabled: yes  


    - name: disable selinux  
      selinux:
        policy: targeted
        state: enforcing

    - name: disable selinux  immediately
      shell: setenforce=0

    - name: make sysctl change
      sysctl:
        name: "{{ item  }}"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables

    - name: load module 
      modprobe:
        name: br_netfilter
        state: present
      tags: modprobe

    - name: install sshpass 
      yum: 
        name: sshpass 
        state: present 
      tags: sshpass

    - name: Remove swapfile from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent
      tags: swap

    - name: Disable swap
      shell: swapoff -a
      tags: swap_now

    - name: Disable firewall
      service: 
        name: firewalld
        state: stopped
        enabled: no


    - name:  switch off swap now 
      shell: swapoff -a
      tags: swap_now


    - name: Configure node ip
      lineinfile:
        path: /etc/sysconfig/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}
        create: yes
      tags: ip_kube

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
        enabled: yes
      tags: restart_kubelet 

    - name: Copy the join command to server location
      copy: src=join-command dest=/tmp/join-command.sh mode=0777

    - name: Join the node to cluster
      command: sh /tmp/join-command.sh

  handlers:
    - name: docker status
      service: name=docker state=started



